apiVersion: devops.alauda.io/v1alpha1
kind: PipelineTemplate
metadata:
  name: SeleniumTest
  namespace: default
  annotations:
    alauda.io/displayName.zh-CN: "测试流水线-Selenium功能UI测试"
    alauda.io/displayName.en: "Selenium Test"
    alauda.io/description.zh-CN: "克隆代码 -> Selenium 测试"
    alauda.io/description.en: "Clone -> Selenium Test"
    alauda.io/version: "1.0.2"
    alauda.io/style.icon: selenium
  labels:
    category: Test
spec:
  engine: graph
  withSCM: true
  agent:
    label: selenium
  stages:
 
  arguments:
   
