apiVersion: devops.alauda.io/v1alpha1
kind: PipelineTemplate
metadata:
  name: SeleniumTest
  namespace: default
  annotations:
    alauda.io/displayName.zh-CN: "测试流水线-Selenium功能UI测试"
    alauda.io/displayName.en: "Selenium Test"
    alauda.io/description.zh-CN: "克隆代码 -> Selenium 测试"
    alauda.io/description.en: "Clone -> Selenium Test"
    alauda.io/version: "1.0.1"
    alauda.io/style.icon: selenium
  labels:
    category: Test
spec:
  engine: graph
  withSCM: true
  agent:
    label: selenium
  stages:
    - name: "Selenium test"
      tasks:
        - name: seleniumTest
          kind: PipelineTaskTemplate
  arguments:
    - displayName:
        zh-CN: "Selenium 测试"
        en: "Selenium Test"
      items:
        - name: "seleniumTest"
          schema:
            type: string
          binding:
            - seleniumTest.args.testPlan
          display:
            type: string
            name:
              zh-CN: "测试计划文件"
              en: "Test plan file"
            description:
              zh-CN: "测试计划文件"
              en: "Test plan file"
          required: true
          value: ""
          default: ''

    - displayName:
        zh-CN: "邮件通知"
        en: "SendMail"
      items:
        - name: "EnableMail"
          schema:
            type: boolean
          binding:
            - seleniumTest.args.EnableMail
          display:
            type: boolean
            name:
              zh-CN: "发送邮件"
              en: "SendMail"
            description:
              zh-CN: "发送邮件"
              en: "SendMail"
          required: false
          value: "false"

        - name: "Notifications"
          schema:
            type: string
          required: false
          binding:
            - seleniumTest.args.Notifications
          value: |
            '[{"name":"test-mail-notification"}]'
          display:
            type: stringMultiline
            advanced: false
            name:
              zh-CN: "通知"
              en: "Notifications"
            description:
              zh-CN: "Json格式，支持逗号分隔的列表。已经定义的通知方式包含了发出、接受对象和模板，不要单引号~~~~"
              en: "Notifications"
          relation:
            - action: show
              when:
                name: EnableMail
                value: true

        - name: "Content"
          schema:
            type: string
          required: false
          binding:
            - seleniumTest.args.Content
          value: |
            '{"BUILD_TIMESTAMP":"${BUILD_TIMESTAMP}","JOB_BASE_NAME":"${JOB_BASE_NAME}","reportLink":"${reportLink}"}'
          display:
            type: stringMultiline
            advanced: false
            name:
              zh-CN: "邮件内容"
              en: "Content"
            description:
              zh-CN: "Json格式邮件内容,不要单引号~~~~"
              en: "Content"
          relation:
            - action: show
              when:
                name: EnableMail
                value: true

